### ISSUE TITLE
Too Many Open Files!

### ISSUE THREAD

**Issue by bentruyman** [tj/search#1]
Let me guess, this is all happening async.

I got this when running through a large project:

```
/usr/local/lib/node_modules/search/bin/search:61
        if (err) throw err;
                 ^
Error: EMFILE, Too many open files
```

**Comment by tj** [comment]
`ulimit -n` :D haha, yeah we should probably cap the parallel stuff, which kinda sucks because it's actually a bit slower than the py one already (not that I've optimized anything at all, seems mostly IO related though)
